CXX = g++

vermelho:
	$(CXX) -o vermelho.o vermelho.cpp
	./vermelho.o

linha:
	$(CXX) -o linha.o linha.cpp
	./linha.o

piccolo: 
	$(CXX) -o piccolo.o piccolo.cpp
	./piccolo.o

clean:
	rm *.o

.PHONY: vermelho linha clean